//
// Created by Jake Dickie on 28/10/2021.
//

#ifndef CPPDESIGNPATTERNSLOWLATENCY_COINBASEORDERMANAGER_H
#define CPPDESIGNPATTERNSLOWLATENCY_COINBASEORDERMANAGER_H


class CoinbaseOrderManager {

};


#endif //CPPDESIGNPATTERNSLOWLATENCY_COINBASEORDERMANAGER_H
