#ifndef CPPDESIGNPATTERNSLOWLATENCY_EXCHANGE_H
#define CPPDESIGNPATTERNSLOWLATENCY_EXCHANGE_H

class Exchange {
 public:
  enum ExchangeName { BITMEX, COINBASE, BINANCE, FTX, KRAKEN, DUMMY };
};

#endif  // CPPDESIGNPATTERNSLOWLATENCY_EXCHANGE_H
