//
// Created by Jake Dickie on 20/10/2021.
//

#ifndef CPPDESIGNPATTERNSLOWLATENCY_SHA256ENGINE_H
#define CPPDESIGNPATTERNSLOWLATENCY_SHA256ENGINE_H

#include <Poco/DigestEngine.h>


#endif //CPPDESIGNPATTERNSLOWLATENCY_SHA256ENGINE_H
